<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class TeamsViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();
        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_teams_view()
    {
        $response = $this->get('trouble-ticket/teams');

        $response->assertStatus(200)->assertViewIs('TroubleTicket::teams.index');
    }

    public function test_trouble_tickets_create()
    {
        $response = $this->get('trouble-ticket/teams/create');

        $response->assertViewIs('TroubleTicket::teams.create_edit')->assertStatus(200);
    }
}
